site_name: Banco de Dados CDD-TD
theme:
  name: material

nav:
  - Guia do Usuário: 
      - Introdução ao projeto: index.md
      - Configuração GitHub: configuracao_github.md
  - Projeto Banco de Dados CDD: 
      - Dados: dados.md
      - Módulos:
          - Funções CDD: funcoes_cdd.md
          - Sharepoint Downloader: sharepoint_downloader.md
          - Views: views.md
      - Pipeline:
          - Atualização Fato CDD: update_fato_cdd.md
          - Atualização Fato TD: update_fato_td.md
          - Atualização Dim CDDD: update_dim_cddd.md
          - Atualização Extras, Acesso e SCDs: update_extras_acesso_scd.md
          - Atualização PBM (Vouchers): update_pbm.md
          - Atualização Ticket Médio: update_ticket_medio.md
          - Auditoria: auditoria.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python



repo_url: https://github.com/easelabs-bianalytics/atualizacao_banco_dados_cdd.git
repo_name: atualizacao_banco_dados_cdd
